### ISSUE TITLE
Don't use <?=

### ISSUE THREAD

**Issue by jenstornell** [Thiousi/kirby-color-list#2]
Many people dont have `<?=` enabled. Instead use `<?php echo`.

**Comment by Thiousi** [comment]
I thought the issue was with <? instead of <?php 
From PHP 5.4 at least. Is this a problem you think ?

**Comment by jenstornell** [comment]
I would not take the risk as I know it's like asking for trouble. Look how the Starterkit does it.

https://github.com/getkirby/starterkit/blob/master/site/snippets/projects.php

**Comment by Thiousi** [comment]
Probably wise! I like the shorthand better but will avoid it ;)

**Comment by jenstornell** [comment]
I would say, use the shorthand when you build stuff for yourself, don't when you build stuff for others. :)

**Comment by Thiousi** [comment]
Fixed! Thanks
